### ISSUE TITLE
Issues on Windows 7

### ISSUE THREAD

**Issue by johngalambos** [conda-forge/neovim-feedstock#2]
Hi,

I'm getting issues with this package running Neovim on Windows 7. 

I have no trouble running the Neovim package from pip. I believe this is because pyuv is specified as a dependency for the Windows flavour of the Neovim python-client:

https://github.com/neovim/python-client/blob/80428b1679fa624431c1da2f9689a6ce7a234097/setup.py#L14-L15

I also assuming the reason pyuv isn't in this recipe is because there isn't an obvious pyuv feedstock? I'm new to conda so not sure how things work yet.

When running

>  :py 42

 in Neovim, I get the following in messages:

```
function provider#python#Call[9]..remote#host#Require[10]..provider#pythonx#Require, line 15
Vim(if):ch 12 was closed by the client
Traceback (most recent call last):^M
  File "<string>", line 1, in <module>^M
  File "C:\Apps\miniconda3\envs\neovim2\lib\site-packages\neovim\__init__.py", line 70, in start_host^M
    session = stdio_session()^M
  File "C:\Apps\miniconda3\envs\neovim2\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 37, in stdio_session^M
    return session('stdio')^M
  File "C:\Apps\miniconda3\envs\neovim2\lib\site-packages\neovim\msgpack_rpc\__init__.py", line 18, in session^M
    loop = EventLoop(transport_type, *args, **kwargs)^M
  File "C:\Apps\miniconda3\envs\neovim2\lib\site-packages\neovim\msgpack_rpc\event_loop\base.py", line 88, in __init__^M
    getattr(self, '_connect_{}'.format(transport_type))(*args)^M
  File "C:\Apps\miniconda3\envs\neovim2\lib\site-packages\neovim\msgpack_rpc\event_loop\asyncio.py", line 93, in _connect_stdio^M
    self._loop.run_until_complete(coroutine)^M
  File "C:\Apps\miniconda3\envs\neovim2\lib\site-packages\trollius\base_events.py", line 348, in run_until_complete^M
    raise RuntimeError('Event loop stopped before Future completed.')^M
RuntimeError: Event loop stopped before Future completed.^M

Failed to load python host. You can try to see what happened by starting nvim with $NVIM_PYTHON_LOG_FILE set and opening the generated log file. Also, the host stderr is available in messages.
E149: Sorry, no help for messagesg
"message.txt" [readonly][unix] 846L, 30209C

```

The Python log file looks like the following:

```
2018-01-23 12:49:23,473 [ERROR @ base_events.py:default_exception_handler:1265] 7012 - Fatal read error on pipe transport
protocol: <neovim.msgpack_rpc.event_loop.asyncio.AsyncioEventLoop object at 0x0000000002B8AC18>
transport: <_ProactorReadPipeTransport fd=0>
Traceback (most recent call last):
  File "C:\Apps\miniconda3\envs\neovim3\lib\asyncio\proactor_events.py", line 202, in _loop_reading
    self._read_fut = self._loop._proactor.recv(self._sock, 4096)
  File "C:\Apps\miniconda3\envs\neovim3\lib\asyncio\windows_events.py", line 430, in recv
    self._register_with_iocp(conn)
  File "C:\Apps\miniconda3\envs\neovim3\lib\asyncio\windows_events.py", line 611, in _register_with_iocp
    _overlapped.CreateIoCompletionPort(obj.fileno(), self._iocp, 0, 0)
OSError: [WinError 6] The handle is invalid
2018-01-23 12:49:23,476 [DEBUG @ base.py:_on_error:166] 7012 - 9
2018-01-23 12:49:23,476 [DEBUG @ base.py:stop:149] 7012 - Stopped event loop
```

Things start working properly after running

> pip install pyuv

Thanks for your work on this package!

**Comment by curtisalexander** [comment]
I'm going to try to replicate using CI &mdash; unfortunately I don't have a Windows machine to test with.

Also, I will try to get [pyuv](https://pypi.python.org/pypi/pyuv) added to the conda-forge channel.  I welcome any help adding pyuv.  If you, or someone else, beat me to adding it conda-forge, I'll update this recipe to include pyuv.

**Comment by curtisalexander** [comment]
@johngalambos I built pyuv and am trying to get it [merged](https://github.com/conda-forge/staged-recipes/pull/5023) into the conda-forge channel.

Once merged, I will update the neovim recipe and test using pyuv as a dependency.

Note that I will be looking to alter this recipe or create a meta package as suggested [here](https://github.com/conda-forge/staged-recipes/issues/4714) to make sure it is clear that this recipe is just for the Python client to neovim and isn't the actual editor.

**Comment by johngalambos** [comment]
@curtisalexander Awesome--thank you!

**Comment by curtisalexander** [comment]
@johngalambos Just updated for 0.2.1 with pyuv as a dependency on Windows. Please let me know if this fixes for you!

**Comment by johngalambos** [comment]
Just tried it out and it works great. Thanks!

**Comment by curtisalexander** [comment]
Excellent!  e4addd9ee758e45ed2db0320e5f9570e52015ff2 closes.
